version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu1804
configuration: Release
only_commits:
  files:
    - appveyor.yml
    - CommandLiners/**/*
    - CommandLiners.Posix/**/*
environment:
  CODECOV_TOKEN: 705f45d2-d219-4cde-8182-d53bae7fb233
  STRYKER_DASHBOARD_API_KEY:
    secure: 7dBuQtP4/QgWdJ7PlawLjYGekTjb3NeCoHco5fmNRfwAhsv+aZCcJkJXHJAY+oYc
  STRYKER_DASHBOARD_PROJECT: CommandLiners
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: minimal
after_test:
  - bash <(curl -s https://codecov.io/bash)
  - dotnet tool install -g dotnet-stryker
  - dotnet stryker --reporters "['dashboard']" --dashboard-project github.com/riezebosch/CommandLiners/master --dashboard-module CommandLiners -tp "['CommandLiners.Tests/CommandLiners.Tests.csproj']" 
  - dotnet stryker --reporters "['dashboard']" --dashboard-project github.com/riezebosch/CommandLiners/master --dashboard-module CommandLiners.Posix -tp "['CommandLiners.Posix.Tests/CommandLiners.Posix.Tests.csproj']" --project-file CommandLiners.Posix/CommandLiners.Posix.csproj
  - dotnet stryker --reporters "['dashboard']" --dashboard-project github.com/riezebosch/CommandLiners/master --dashboard-module CommandLiners.CommandLineUtils -tp "['CommandLiners.CommandLineUtils.Tests/CommandLiners.CommandLineUtils.Tests.csproj']" --project-file CommandLiners.CommandLineUtils/CommandLiners.CommandLineUtils.csproj
  - dotnet stryker --reporters "['dashboard']" --dashboard-project github.com/riezebosch/CommandLiners/master --dashboard-module CommandLiners.MonoOptions -tp "['CommandLiners.MonoOptions.Tests/CommandLiners.MonoOptions.Tests.csproj']" --project-file CommandLiners.MonoOptions/CommandLiners.MonoOptions.csproj
deploy:
- provider: NuGet
  api_key:
    secure: JzBmBwf9nOxIvQ2bmLFJEVfH+vjRcLDERSc2enRfSjOo6/PvhC8nx6EJF8kCHarY
  on:
    branch: master